config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users, controllers: {registrations: :registrations}
  resources :search, only: [:index]
  resources :users, only: [:show]
  get 'hello_world', to: 'hello_world#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#home'

  get 'welcome/edit_bartenders'
  get 'welcome/users'
  get 'welcome/not_proper_age'
  get 'welcome/search'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :bartender, :class_name => 'User'
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  scope :bartender, -> { where(bartender: true ) }
  scope :regular, -> { where(bartender: [nil, false] ) }
  
  has_many :events
  has_many :jobs, class_name: "Event", foreign_key: "bartender_id"

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one_attached :picture

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :by_resource
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
 
 


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
      keys:
      [:name, :bartender, :proper_age, :rate, :home_address, :travel_radius,
       :standard, :flair, :mixologist, :gender, :picture, :rating, :monday, :tuesday, :wednesday,
       :thursday, :friday, :saturday, :sunday])
  end




  private

    def by_resource
      if devise_controller?
        "devise"
      else
        "application"
      end

    end



  end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  # skip_before_action :authenticate_user!, raise: false
  skip_before_action :verify_authenticity_token, :authenticate_user!

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
    # @events = current_user.jobs
    respond_to do |format|
      format.html
      format.json do
        render json:  @events.map do |event|
                        event.attributes.merge(
                          bartender: event.bartender.name,
                          user: event.user.name
                        )
                      end
      end
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params.merge(user: current_user))
    respond_to do |format|
      if @event.save!
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:user_id, :location, :name, :date, :confirmed, :bartender_id)
    end
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    

def update
 @user = current_user
 data = params["user"]
 @user.rate= data["rate"]
 @user.home_address= data["home_address"]
 @user.travel_radius= data["travel_radius"]
 @user.standard = data["standard"]
 @user.flair = data["flair"]
 @user.mixologist= data["mixologist"]
 @user.gender = data["gender"]
 @user.bio = data["bio"]
 @user.rating = data["rating"]
 @user.monday = data["monday"]
 @user.tuesday= data["tuesday"]
 @user.wednesday = data["wednesday"]
 @user.thursday = data["thursday"]
 @user.friday = data["friday"]
 @user.saturday = data["saturday"]
 @user.sunday = data["sunday"]
 @user.picture.attach(data["picture"])
 @user.save
 redirect_to @user
end




    def after_sign_up_path_for(resource)
        @user = current_user
        if not resource.proper_age 
            welcome_not_proper_age_path
        elsif resource.bartender
            welcome_edit_bartenders_path 
        else
            root_path
        end
    end

   
    
   







end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json do
        results = User.bartender
        @results = results.map do |result|
          result.attributes.merge(location: user_path(result))
        end
        render json: @results
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def edit

  end

def user_params
params.require(:user).permit(:picture)

end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def edit_bartenders
    end

  
    def not_proper_age
    end




end

app/helpers/application_helper.rb
module ApplicationHelper

    def resource_name
        :user
      end
    
      def resource
        @resource ||= User.new
      end
    
      def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
      end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

     <%# <div class="field"> %>
    <%#= form.label :name %>
    <%#= form.text_field :name %>
  <%# </div> %>

  <%# <div class="field"> %>
    <%#= form.label :location %>
    <%#= form.text_field :location %>
  <%# </div> %>

    <%# <div class="field"> %>
    <%#= form.label :date %>
    <%#= form.text_field :date %>
  <%# </div> %>


  <div class="field">
    <%= form.label :confirmed %>
    <%= form.check_box :confirmed %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<body class = "Event-text-color">
    <nav class="navbar navbar-expand-lg black fixed-top scrolling-navbar">
      		<div class="container">
        		<img src="/assets/side-view-logo.png" width="50%", alt="logo" >
      		</div>
          		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
            			aria-expanded="false" aria-label="Toggle navigation">
                		<span class="navbar-toggler-icon dark-amber-text"></span>
          		</button>
			<div class="collapse navbar-collapse" id="basicExampleNav">
				<ul class="navbar-nav mr-auto links-in-nav">
          <li class="nav-item">
              <%= link_to 'Home', root_path, :style => "color:white; font-size: 7px;margin-left:400px;", :class =>"btn orange btn-sm" %>
          </li>
           <li class="nav-item">
              <%= link_to 'Search',  welcome_search_path, :style => "color:white; font-size: 7px;", :class =>"btn orange btn-sm"%>
          </li>
					<li class="nav-item">
							<% if current_user %>
									<%= link_to 'Sign Out', destroy_user_session_path, method: :delete,  :style => "color:white; font-size: 7px;",  :class =>"btn orange btn-sm" %>
							<% end %>
					</li>
				</ul>
			</div>
		</nav>
    <div class="container-fluid events-confirmed">

    <h1 class="h1-events">Confirm your Event</h1>
		<div class="box-form">
			<%= render 'form', event: @event %>
		</div>
			<%= link_to 'Show', @event ,  :style => "color:white; font-size: 7px;",  :class =>"btn orange btn-sm"   %> |
			<%= link_to 'Back', events_path ,  :style => "color:white; font-size: 7px;",  :class =>"btn orange btn-sm"  %>
    </div>
</body>

app/views/events/index.html.erb
<%# <p id="notice"><%= notice %>
<body class ="Event-text-color">
  		<nav class="navbar navbar-expand-lg black fixed-top scrolling-navbar">
      		<div class="container">
        		<img src="/assets/side-view-logo.png" width="50%", alt="logo" >
      		</div>
          		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
            			aria-expanded="false" aria-label="Toggle navigation">
                		<span class="navbar-toggler-icon dark-amber-text"></span>
          		</button>
			<div class="collapse navbar-collapse" id="basicExampleNav">
				<ul class="navbar-nav mr-auto links-in-nav">
          <li class="nav-item">
              <%= link_to 'Home', root_path, :style => "color:white; font-size: 7px;margin-left:400px;", :class =>"btn orange btn-sm" %>
          </li>
           <li class="nav-item">
              <%= link_to 'Search',  welcome_search_path, :style => "color:white; font-size: 7px;", :class =>"btn orange btn-sm"%>
          </li>
					<li class="nav-item">
							<% if current_user %>
									<%= link_to 'Sign Out', destroy_user_session_path, method: :delete,  :style => "color:white; font-size: 7px;",  :class =>"btn orange btn-sm" %>
							<% end %>
					</li>
				</ul>
			</div>
		</nav>
<div class="container-fluid event-table">
<h2 class ="myHeading"> Your Events</h2>

<table class= "myTable">
  <thead>
    <tr class= "tr">
      <th class ="th">Name of Employer</th>
      <th class ="th">Name of Event</th>
      <th class ="th">Location</th>
      <th class ="th">Date</th>
      <th class ="th">Confirmed status</th>
      <th class ="th"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr class= "tr">
        <td class = "td"><%= event.user.name %></td>
        <td class = "td"><%= event.name %></td>
        <td class = "td"><%= event.location %></td>
        <td class = "td"><%= event.date %></td>
        <% if event.confirmed %>
          <td class = "td">Confirmed</td>
          <% else %>
          <td class = "td">Not Confirmed</td>
        <% end%>

        <%# <td><%= link_to 'Show', event %>
        <%#</td> %>
        <td class ="td"><%= link_to 'Confirm Request', edit_event_path(event), :class => "linkForRequest" %></td>
        <%# <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
       <%# </td> %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>
</body>
<%# <%= link_to 'New Event', new_event_path %> 

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<%# <p id="notice"><%= notice %>
<div class="container">
  <nav class="navbar navbar-expand-lg black fixed-top scrolling-navbar">
    <div class="container">
      <img src="/assets/side-view-logo.png" width="50%", alt="logo" >
    </div>
    	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
            	aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon dark-amber-text"></span>
      </button>
		<div class="collapse navbar-collapse" id="basicExampleNav">
			<ul class="navbar-nav mr-auto links-in-nav">
        <li class="nav-item">
            <%= link_to 'Home', root_path, :style => "color:white; font-size: 7px;margin-left:400px;", :class =>"btn orange btn-sm" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Search',  welcome_search_path, :style => "color:white; font-size: 7px;", :class =>"btn orange btn-sm"%>
        </li>
				<li class="nav-item">
					<% if current_user %>
						<%= link_to 'Sign Out', destroy_user_session_path, method: :delete,  :style => "color:white; font-size: 7px;",  :class =>"btn orange btn-sm" %>
					<% end %>
				</li>
			</ul>
		</div>
	</nav>
  <div class="events-confirmed">
    <p class="p-bar">
      Name:
      <%= @event.name %>
    </p>

    <p class="p-bar">
      <strong>Location:</strong>
      <%= @event.location %>
    </p> 

    <p class="p-bar">
      <strong>Date:</strong>
      <%= @event.date %>
    </p> 

    <%# <p class="p-bar"> %>
      <%# <strong>Confirmed:</strong> %>
      <%#= @event.confirmed %>
    <%# </p>  %>

<%#= link_to 'Edit', edit_event_path(@event) %> 
<%= link_to 'Back', events_path, :style => "color:white;", :class => "btn orange btn-sm" %>
  </div>
</div>

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component 'App', props: {user: current_user} %>
<%#= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>CocktailParty</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'App' %>

    <link href="https://fonts.googleapis.com/css?family=Do+Hyeon" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Abel" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Viga" rel="stylesheet">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

		<!-- Font Awsome -->
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
		

     <!-- Bootstrap core CSS -->
     <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
     <!-- Material Design Bootstrap -->
     <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/css/mdb.min.css" rel="stylesheet">
       <!-- Font Awesome -->
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
     <!-- Bootstrap core CSS -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<link rel="stylesheet" href="css/responsive.css">
		<link rel="stylesheet" href="css/animate.min.css">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    </head>

  <body>
    <%= yield %>


      <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/js/mdb.min.js"></script>

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cocktail Party</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Bootstrap core CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/css/mdb.min.css" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
 
  <body>
    <nav class="navbar navbar-dark black">

      <%# <a class="navbar-brand" href="#"> %>
      					<img id="logo"src="/assets/side-view-logo.png" width="30%", alt="logo" >

       <%#= image_tag 'cocktail-party.png', height:'120x120', alt: "logo" %>
      <%# </a> %>

     </nav> 


    <%# <nav class="navbar navbar-expand-lg black fixed-top scrolling-navbar">
				<div class="container">
					<img id="logo"src="/assets/side-view-logo.png" width="50%", alt="logo" >
				</div> %>
    <%= yield %>
    <!-- JQuery -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.5.4/js/mdb.min.js"></script>
  </body>
</html>

app/views/users/show.html.erb
<div class="container">
   <nav class="navbar navbar-expand-lg black fixed-top scrolling-navbar">
      <div class="container">
        <img src="/assets/side-view-logo.png" width="50%", alt="logo" >
      </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
            aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon dark-amber-text"></span>
          </button>
        <div class="collapse navbar-collapse" id="basicExampleNav">
          <ul class="navbar-nav mr-auto links-in-nav">
            <li class="nav-item">
              <%= link_to 'Home', root_path, :style => "color:white; font-size: 7px;", :class => "btn orange btn-sm" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Search',  welcome_search_path, :style => "color: white; font-size: 7px;",:class => "btn orange btn-sm" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :style => "color:white; font-size: 7px;", :class => "btn orange btn-sm"%>
            </li>
          </ul>
      </div>
   </nav>
  <div id="bar-page">
  <div class="bar-container">
    <div class="row">
      <div class="col-xs-12 col-sm-5">
        <div class="bar-picture">
          <p class="p-bar img-user">
            <%= image_tag(@user.picture, :size => "300x350") %>
          </p>
        </div>
      </div>

      <div class="col-xs-12 col-sm-5 text-field">
          <div class="bar-profile title-bar">
            <h1 id="h1-bar">Part-time Bartender:</h1>
              <p class="user-name">
               <%= @user.name %>
              </p>
          </div>
          
          <div class="bar-profile bar-profile-2">
            <div class="info-text">
            Gender:
            <p class="p-bar">
              <%= @user.gender %>
            </p>
            </div>
        
          <div class="info-text">
            Rate:
            <p class="p-bar">
                <%= @user.rate%>
            </p>
          </div>

  
          <div class="info-text">
                Bartender:
            <p class="p-bar">
              <%= if @user.standard
                  p "standard"
                  end %>
              <%= if @user.flair
                  p "flair"
                  end %>
              <%= if @user.mixologist
                 p "mixologist"
                  end %>

            </p>
          </div>
           </div>

          <div class="bar-profile info-text">
               Bio:
            <p class="p-bar bio">
                <%= @user.bio %>
            </p>
          </div>

          <div class="bar-profile links-to">
            <ul class="links-to-li">
              <li class="links-to-links">
                  <%= link_to 'Edit', welcome_edit_bartenders_path, :style => "color:white; font-size: 15px;", :class => "btn orange btn-sm" %>
              </li>
              <li class="links-to-links">
                  <%= link_to "Back", welcome_search_path(resource_name), :style => "color:white; font-size: 15px;", :class => "btn orange btn-sm" %>
              </li>
            </ul>
          </div>
      </div>
      <div class="col-xs-12 col-sm-2">
          <div class="events">
                  <%= link_to 'See your events', events_path, :style => "color:white; font-size: 15px;", :class => "btn orange btn-sm" %> 
          </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_bio.html.erb
<%= form_for(resource, as: resource_name, url: user_registration_path(resource_name), html: {method: :patch}) do |f| %>
    <div class="md-form">
        <%= f.text_field :gender, class: "form-control", placeholder: "Gender", value: current_user.gender %>
    </div>
    <div class="md-form">
        <%= f.text_field :rate, class: "form-control", placeholder: "Wage per Hour", value: current_user.rate %>
    </div>
    <div class="md-form">
        <%= f.text_field :home_address, class: "form-control",  placeholder: "Home Address",value: current_user.home_address %>
    </div>
    <div class="md-form" >
        <%= f.text_field :travel_radius, class: "form-control",  placeholder: "Travel radius",value: current_user.travel_radius %>
    </div>
    <div class="md-form">
        <h6 class="card-title text-center">Write your Bio:</h6>
        <div class="md-form indigo-text">
            <%= f.text_field :bio, class: "form-control" , value: current_user.bio%>
        </div>
    </div>
    <div class="md-form">
        <h6 class="card-title text-center">Add your Profile Picture</h6>
        <div class="md-form text-center">
            <%= f.file_field :picture%>
        </div>
    </div>
<% end %>

app/views/welcome/_form.html.erb
<div class="container card">
  <div class="card-body">
    <h4 class="card-title text-center">More Information</h4>
      <%= render partial: 'bio' %>
  </div>
  <div class="card-body">
    <h6 class="card-title text-center">Check Off Your Speciality:</h6>
      <%= render partial: 'speciality' %>
  </div>
  <div class="card-body">
    <h6 class="card-title text-center">Your availablilty:</h6>
      <%= render partial: 'weekdays' %>
  </div>
</div>

app/views/welcome/edit_bartenders.html.erb
<div class="more-info">
<div class="nav-cocktail">
    <%= render partial: 'nav' %>
</div>
<div class="edit-bartender-form">
        <%= render 'form' %>
    </div>
</div>

app/views/welcome/home.html.erb
<body>
	<!--Main Navigation-->
	<header>
		<nav class="navbar navbar-expand-lg black fixed-top scrolling-navbar">
      		<div class="container">
        		<img src="/assets/side-view-logo.png" width="50%", alt="logo" >
      		</div>
          		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
            			aria-expanded="false" aria-label="Toggle navigation">
                		<span class="navbar-toggler-icon dark-amber-text"></span>
          		</button>
			<div class="collapse navbar-collapse" id="basicExampleNav">
				<ul class="navbar-nav mr-auto links-in-nav">
					<li class="nav-item">
							<% if current_user %>
									<%= link_to 'Sign Out', destroy_user_session_path, method: :delete,  :style => "color:white; font-size: 7px; margin-left:450px;", :class => "btn orange btn-sm" %>
							<% end %>
					</li>
				</ul>
			</div>
		</nav>
			<div class="container d-flex align-items-center justify-content-center h-100">
				<div>
						<video id="bgvid" playsinline autoplay muted loop><source src="bartender.mp4" type="video/mp4"></video>
				</div>
				<div class="row d-flex justify-content-center text-center">
						<div class="col-md-10">
								<!-- Heading -->
								<h2 class="h2-home" class="display-10 font-weight-bold white-text pt-5 mb-2">Hire A Bartender</h2>

								<!-- Divider -->
								<hr class="hr-light">

								<!-- Description -->
								<h4 class="h4-home"class="white-text my-4"> Start here by searching through our list of talented bartenders</h4>
								<% if current_user %>
										<%= link_to '<button id="search-btn" type="button" >SEARCH</button>'.html_safe, welcome_search_path %>
								<% else %>
								<%= link_to '<button id="sign-in-btn" type="button" >SIGN IN</button>'.html_safe, user_session_path %>
								<% end %> 
						</div>
				</div>
			</div>
	</header>

	<!--========== Features ==========--> 

	<section class="features">
		<div class="features-overlay">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
									
									<!-- indicators -->
									<ol class="carousel-indicators">
										<li data-target="#carousel-features" data-slide-to="0" class="active"></li>
										<li data-target="#carousel-features" data-slide-to="1"></li>
										<li data-target="#carousel-features" data-slide-to="2"></li>
									</ol>

									<!-- wrapper for slides -->
									<div class="carousel-inner">

										<!-- item 01 -->
										<div class="carousel-item text-center active">
											<img class="d-block w-20" src="/assets/miami.jpg" alt="features" class="center-block">
											<div class="features-caption">
												<h2>Community</h2>
												<h4>
												<p>We are community based and focus on bringing professionals in your area</p>
											</div>
										</div>

										<!-- item 02 -->
										<div class="carousel-item text-center">
											<img class="d-block w-20" src="/assets/bartender.jpg" alt="features" class="center-block">
											<div class="features-caption">
												<h2>Book Bartenders</h2>
												<h4>
												<p>You have more control on who you want to book. Our bartenders are chosen from a peer-to-peer user rating scale.
												</p>
											</div>
										</div>

										<!-- item 03 -->
										<div class="carousel-item text-center">
											<img class="d-block w-20" src="/assets/cheers.jpg" alt="features" class="center-block">
											<div class="features-caption">
												<h2>Find Events</h2>
												<h4>
												<p>As a bartender looking to book events, you don’t need to be fancy to make drinks as long as you have a excellent
													presentation and a pleasing personality.</p>
											</div>
										</div>
									</div>
									<a class="carousel-control-prev" href="#carousel-features" role="button" data-slide="prev">
										<span class="carousel-control-prev-icon" aria-hidden="true"></span>
										<span class="sr-only">Previous</span>
									</a>
									<a class="carousel-control-next" href="#carousel-features" role="button" data-slide="next">
										<span class="carousel-control-next-icon" aria-hidden="true"></span>
										<span class="sr-only">Next</span>
									</a>
						</div>
					</div>
				</div>
			</div>
		</div>

	</section>

</body>

app/views/welcome/not_proper_age.html.erb
<body id="spilled-drink" >
	
	<div id="age-limit">
			<h1>You need to be over 21 to enter this site.</h1>
	</div>

</body>